// Generated by svelte-check-rs
// This file is for type-checking only

import type { PageProps } from './$types';

import "../../__svelte_check_rs_helpers";


// === TEMPLATE TYPE-CHECK BLOCK ===
// This is never executed, just type-checked
async function __svelte_template_check__() {
  __svelte_create_element("div", {}, {
    id: "pragma-test",
    tabindex: 0,
  });
  __svelte_create_element("div", {}, {
    id: "no-pragma-test",
    tabindex: 0,
  });
}

// === COMPONENT TYPE EXPORT ===
type __SvelteProps_Page_ = {};
declare const __SvelteComponent_Page_: __SvelteComponent<__SvelteProps_Page_>;
export default __SvelteComponent_Page_;
