// Generated by svelte-check-rs
// This file is for type-checking only


import "../../__svelte_check_rs_helpers";

// === INSTANCE SCRIPT ===

	// This file has intentional TypeScript errors
	// It should be excluded from type checking via tsconfig.json "exclude"

	const x: string = 123; // Type error
	const y: number = "hello"; // Type error


// === TEMPLATE TYPE-CHECK BLOCK ===
// This is never executed, just type-checked
async function __svelte_template_check__() {
  x;
  y;
}

// === COMPONENT TYPE EXPORT ===
type __SvelteProps_Broken_ = {};
declare const __SvelteComponent_Broken_: __SvelteComponent<__SvelteProps_Broken_>;
export default __SvelteComponent_Broken_;
