// Generated by svelte-check-rs
// This file is for type-checking only


import "../../__svelte_check_rs_helpers";


// === TEMPLATE TYPE-CHECK BLOCK ===
// This is never executed, just type-checked
async function __svelte_template_check__() {
  __svelte_create_element("div", {}, {
    tabindex: 0,
  });
}

// === COMPONENT TYPE EXPORT ===
type __SvelteProps_Test_ = {};
declare const __SvelteComponent_Test_: __SvelteComponent<__SvelteProps_Test_>;
export default __SvelteComponent_Test_;
