// Generated by svelte-check-rs
// This file is for type-checking only

import type { LayoutProps } from './$types';

import "../../../../__svelte_check_rs_helpers";

// === INSTANCE SCRIPT ===

	let { children } = ({} as __SvelteLoosen<LayoutProps>);


// === TEMPLATE TYPE-CHECK BLOCK ===
// This is never executed, just type-checked
async function __svelte_template_check__() {
  __svelte_create_element("link", {}, {
    rel: "manifest",
    href: "/manifest.json",
  });
  __svelte_create_element("meta", {}, {
    name: "theme-color",
    content: "#667eea",
  });
  __svelte_create_element("meta", {}, {
    name: "mobile-web-app-capable",
    content: "yes",
  });
  __svelte_create_element("meta", {}, {
    name: "apple-mobile-web-app-status-bar-style",
    content: "black-translucent",
  });
  __svelte_create_element("link", {}, {
    rel: "apple-touch-icon",
    href: "/icon-192.svg",
  });
  children();
}

// === COMPONENT TYPE EXPORT ===
type __SvelteProps_Layout_ = { children: unknown };
declare const __SvelteComponent_Layout_: __SvelteComponent<__SvelteProps_Layout_>;
export default __SvelteComponent_Layout_;
